services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
